# Generated by Django 3.0.7 on 2020-09-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='somestring', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='somestring', max_length=50, unique=True),
        ),
    ]
