# Generated by Django 3.0.7 on 2020-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20200901_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggest', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
