# Generated by Django 3.0.7 on 2020-09-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20200902_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggest',
            new_name='text',
        ),
    ]
