# Generated by Django 3.0.7 on 2020-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20200902_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(default='abc', max_length=300),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='text',
            field=models.CharField(default='abc', max_length=300),
        ),
    ]
