# Generated by Django 3.0.7 on 2020-09-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20200902_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='title',
        ),
    ]
