# Generated by Django 3.0.7 on 2020-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20200904_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(default='abc', max_length=300),
        ),
    ]
