# Generated by Django 3.0.7 on 2020-09-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_auto_20200916_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={},
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='created',
            new_name='date',
        ),
    ]
